Manav
MailerDaemonISM/Placementor pull request #12
Opened 2023-08-12 08:52 UTC by mysticalmanav

@Mayank2602 @ramansain20 @Parth-kumar-1802  Sir changed all the filed as said. Please review

2023-08-13 08:13 UTC, Mayank2602 requested changes

2023-08-13 08:13 UTC, Mayank2602 commented on src/components/InsightsComponents/InsightPlacement2021.js
Check default nomenclature for useState

2023-08-13 08:13 UTC, Mayank2602 commented on src/components/InsightsComponents/InsightPlacement2021.js
Remove Console.logs. 
Modify the names for methods handle and input handler to something relevant

2023-08-13 08:13 UTC, Mayank2602 commented on src/components/InsightsComponents/InsightPlacement2021.js
>                    <BranchLink onClick={(e)=>handle(e)} name ='ce'>
Improve this code by getting all the branch names from an array and looping over it to create the dropdown instead of this.

2023-08-13 08:30 UTC, mysticalmanav commented on src/components/InsightsComponents/InsightPlacement2021.js
Ok sir, Changed

2023-08-13 08:33 UTC, mysticalmanav commented on src/components/InsightsComponents/InsightPlacement2021.js
>                    <BranchLink onClick={(e)=>handle(e)} name ='ce'>
Ok sir, evening tak kardunga

2023-08-19 10:13 UTC, Mayank2602 submitted a review, later dismissed
I created a helper folder with a file called ConsoleHelper.js

const ConsoleHelper = (data) => {
  if (process.env.NODE_ENV === 'production') return;
  console.log(data);
}

export default ConsoleHelper;
So, instead of console.log(data) do ConsoleHelper(data);

Can we do something like this to avoid getting log statements in production?

2023-08-19 10:24 UTC, Mayank2602 commented on src/components/InsightsComponents/InsightPlacement2021.js
>                    <BranchLink onClick={(e)=>handle(e)} name ='ce'>
The array implementation is not yet done? Just loop over the array instead of writing 
  <BranchLink onClick={(e)=>handle(e)} name ='che'>
                    CHE
                  </BranchLink>
each time. In if you have branch in array you can just write something like
for( branch: arrayOfBranches) :
  <BranchLink onClick={(e)=>handle(e)} name =branch>
                    toUpper(branch) 
                  </BranchLink>
// check the syntax and function to be used.

2023-08-20 17:15 UTC, mysticalmanav commented on src/components/InsightsComponents/InsightPlacement2021.js
>                    <BranchLink onClick={(e)=>handle(e)} name ='ce'>
Sir it is already done please check the commit "files updated"

2023-08-20 17:20 UTC, mysticalmanav commented
> I created a helper folder with a file called ConsoleHelper.js
> 
> const ConsoleHelper = (data) => { if (process.env.NODE_ENV === 'production') return; console.log(data); }
> 
> export default ConsoleHelper; So, instead of console.log(data) do ConsoleHelper(data);
> 
> Can we do something like this to avoid getting log statements in production?

Yes sir but where and why we have to do it please tell.

2023-10-04 12:25 UTC, Parth-kumar-1802 approved these changes

2023-10-06 11:35 UTC, merged