Update Data.js
MailerDaemonISM/Placementor pull request #4
Opened 2023-08-07 15:15 UTC by Ansh845

@Mayank2602 @Parth-kumar-1802  please review

2023-08-07 16:06 UTC, Mayank2602 requested changes

2023-08-07 16:06 UTC, Mayank2602 commented on src/components/Data.js
Redundant spaces.

2023-08-07 16:06 UTC, Mayank2602 commented on src/components/Data.js
> +
remove this blank line.

2023-08-07 16:06 UTC, Mayank2602 commented on src/components/Data.js
>    console.log(data.influence_of.PORs);
Remove console.logs

2023-08-07 16:06 UTC, Mayank2602 commented on src/components/Data.js
> +
Remove blank lines.

2023-08-07 16:08 UTC, Mayank2602 commented
Another overall change to be made:
You do not need to explain how a certain piece of code is working. (for eg. what && does or what .map method does.) . Just a comment above the particular block code describing what it does on a high level is fine.
Remove the comments accordingly.

2023-08-09 10:42 UTC, Mayank2602 requested changes

2023-08-09 10:42 UTC, Mayank2602 commented on src/components/Data.js
> +//styles.
Styles to be imported from a single file?

2023-08-09 10:42 UTC, Mayank2602 commented on src/components/Data.js
> +  const [companyInfo, setAllCompaniesData] = useState({
Nomenclature rules?
change to companyInfo , setCompanyInfo

2023-08-09 10:42 UTC, Mayank2602 commented on src/components/Data.js
> +{/*The following data loads when we click on any company to view them.*/}
This comment can be removed.

2023-08-09 10:42 UTC, Mayank2602 commented on src/components/Data.js
>          {console.log(data)}
remove console logs?

2023-08-09 10:42 UTC, Mayank2602 commented on src/components/Data.js
>                <li style={{
Please fix and push the code at once.

2023-08-13 09:00 UTC, Ansh845 commented on src/components/Data.js
> +
resolved

2023-08-13 09:00 UTC, Ansh845 commented on src/components/Data.js
> +
removed !

2023-08-13 09:01 UTC, Ansh845 commented on src/components/Data.js
>    console.log(data.influence_of.PORs);
all the console.logs have been removed

2023-08-13 13:34 UTC, Ansh845 commented on src/components/Data.js
>                <li style={{
I have resolved this...Has put the styles in data-module.css and extracted from there....But I had a little issue naming them so I have named it very casually right now.

2023-08-13 13:36 UTC, Ansh845 commented on src/components/Data.js
> +//styles.
The styles that are present at the top of const Data are yet to be transfered to a css file for exporting because I am facing a little issue over managing them. I dont understand how to rewrite this code in the css file for extraction...container classes like div are mentioned along them.

2023-08-13 13:36 UTC, Ansh845 commented on src/components/Data.js
> +  const [companyInfo, setAllCompaniesData] = useState({
Resolved !

2023-08-13 13:36 UTC, Ansh845 commented on src/components/Data.js
> +{/*The following data loads when we click on any company to view them.*/}
Yes,,,I have removed this comment now.

2023-08-13 13:37 UTC, Ansh845 commented on src/components/Data.js
>          {console.log(data)}
Removed this with the new commit.

2023-10-04 12:15 UTC, Parth-kumar-1802 approved these changes

2023-10-04 12:15 UTC, merged