Divya
MailerDaemonISM/Placementor pull request #5
Opened 2023-08-08 06:05 UTC by divyaagit

@Mayank2602  @Parth-kumar-1802 please review

2023-08-08 06:27 UTC, Parth-kumar-1802 commented on src/components/HomeComponents/Insight.js
> +// Styling for the Heading Component.
not needed

2023-08-08 06:29 UTC, Parth-kumar-1802 commented on src/components/HomeComponents/Insight.js
> +// Styling for the Heading Component.
keep the styled components in a seperate file... name it something like "InsightStyles.js"
refer to this
https://stackoverflow.com/questions/52991728/how-to-export-styled-component-from-a-file

2023-08-08 13:26 UTC, divyaagit commented on src/components/HomeComponents/Insight.js
> +// Styling for the Heading Component.
okay sir . I'll make the changes

2023-08-09 10:51 UTC, Mayank2602 requested changes

2023-08-09 10:51 UTC, Mayank2602 commented on src/pages/Home.js
>  import PastRecruiter from "../components/HomeComponents/PastRecruiter";
Please check if we are using pastRecruiters in this file. Remove the unnecessary imports.

2023-08-09 10:51 UTC, Mayank2602 commented on src/pages/Home.js
>  const Card = styled.div`
Card style is used in multiple files. Can we export it from a single file instead of re declaring.

2023-08-09 10:51 UTC, Mayank2602 commented on src/pages/Home.js
>            href="https://github.com/MejarKumar/All-Company-Logo/blob/main/favicon-32x32.png?raw=true"
Similarily, can we create a module to import links from instead of directly writing them here. Can you explore if it will be better to download the image than use a github link?

2023-08-09 12:01 UTC, divyaagit commented
okay sir, I'll make the changes

2023-08-09 12:02 UTC, divyaagit commented on src/pages/Home.js
>  const Card = styled.div`
okay sir. I'll make the changes.

2023-08-10 08:42 UTC, divyaagit commented on src/components/HomeComponents/Insight.js
> +// Styling for the Heading Component.
Sir, I have created a new file for the styles.

2023-08-10 08:43 UTC, divyaagit commented on src/pages/Home.js
>  import PastRecruiter from "../components/HomeComponents/PastRecruiter";
Sir, we are using pastRecruiters in the file. I have also confirmed from the website.

2023-08-10 08:44 UTC, divyaagit commented on src/pages/Home.js
>  const Card = styled.div`
Sir, I have created a new file for the styles in the folder and then imported them.

2023-10-04 12:18 UTC, Parth-kumar-1802 approved these changes

2023-10-04 12:23 UTC, merged